### ISSUE TITLE
pn532

### ISSUE THREAD

**Issue by WEIWULUNLUN** [UnicornTeam/HackCube-Special#1]
有没有考虑过把pn532加进去呢？

**Comment by WEIWULUNLUN** [comment]
一个cc1101可以工作在315和433频率？

**Comment by DroidKali** [comment]
可以的，官方有说明文档，可以去看看

**Comment by WEIWULUNLUN** [comment]
@DroidKali 我并没有买到这个，看到论坛上上有diy的教程中给出的模块购买连接中的cc1101并不支持315mhz

**Comment by WEIWULUNLUN** [comment]
![2036142829](https://user-images.githubusercontent.com/43396706/57931013-00a4ee00-78ea-11e9-9179-2a01c8546921.jpg)

**Comment by DroidKali** [comment]
cc1101硬件上支持433/315/868/915MHz的，可以根据客户端软件调整所需的频率

**Comment by WEIWULUNLUN** [comment]
感谢解答
