### ISSUE TITLE
Atmega32u4 not working

### ISSUE THREAD

**Issue by Sboeli** [UnicornTeam/HackCube-Special#2]
The atmega32u4 board can't be found by windows 10 after schets compile and upload. Windows 10 can't identify usb. The usb port above the on/off buton. no com port assigned in Ide.
Reloading and updating usb drivers dit not solve. How to recover the board?

**Comment by daliyYang** [comment]
Hi，according to your description ,you need to rewrite boot loader for atmega32u4 with USB tinny.

**Comment by HuangLinBUPT** [comment]
Please rewrite boot loader for atmega32u4 with USB tinny
